version: 2.1
executors:
  android-executor:
    docker:
      - image: circleci/android:api-30-node
    working_directory: ~/app

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Set up Java
          command: >
            echo y | sdkmanager --install 'platforms;android-30';
            echo y | sdkmanager --install 'build-tools;30.0.3';
            echo y | sdkmanager --install 'platform-tools'
      - run:
          name: Install Astrology
          command: |
            curl -sSL https://get.astrology.dev | bash
      - run:
          name: Install Dependencies
          command: astrology resolve
      - run:
          name: Build Project
          command: ./gradlew assembleDebug

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
